# Homework

Write a function that receives as input a 2D boolean NumPy array and outputs the coordinates of the minimal bounding-box that encloses all non-zero elements in the input array. Try to make your code clear and with fast execution.

![../Figures/bbox.png](../Figures/bbox.png)

**Learning goals**:
- Learn to define NumPy functions
- Development of efficient NumPy array processing skills
- Getting familiarity with NumPy functions
    
**Tip:** search for the function nonzero in the NumPy documentation.

**Rules:**
- All solutions will be visible to all students from initial development to the final code;
- If you got your implementation idea from someone else, give credit to that person;
- If you have a suggestion to improve a friend’s code, leave a suggestion.

##  Template Function

In [1]:
import numpy as np

def bbox_loop(bool_img):
    """
    Input: 2D boolean NumPy array
    Output: r1, c1, r2, c2 -> coordinates of the minimal bounding-box that encloses all non-zero elements in the input array
            r1 -> minimum row
            c1 -> minimum column
            r2 -> maximum row
            c2 -> maximum columns
    """
    ## Tis is a slow loop-based solution
    r1,c1 = bool_img.shape
    r2,c2 = 0,0
    for row in range(bool_img.shape[0]):
        for column in range(bool_img.shape[1]):
            if bool_img[row,column]!= 0:
                if row < r1:
                    r1 = row
                if column < c1:
                    c1 = column
                if r2 < row:
                    r2 = row
                if c2 < column:
                    c2 = column
    # Remember the last index is not incldued in the slicing so we have to add 1            
    r2+=1 
    c2+=1
    return r1,c1,r2,c2

def my_bbox(bool_img):
    """
    Input: 2D boolean NumPy array
    Output: r1, c1, r2, c2 -> coordinates of the minimal bounding-box that encloses all non-zero elements in the input array
            r1 -> minimum row
            c1 -> minimum column
            r2 -> maximum row
            c2 -> maximum columns
    """

    # Write your function below
    r1,c1 = 0,0
    r2,c2 = bool_img.shape
    
    return r1,c1,r2,c2
    
    

## Test Cases

### Test 01 - small triangle

In [2]:
# Triangle test case
test01 = np.zeros((10,10),dtype = bool)
test01[2,5] = True
test01[8,3] = True
test01[8,7] = True
print(test01.astype(int))

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [3]:
print(bbox_loop(test01))
print(my_bbox(test01))

(2, 3, 9, 8)
(0, 0, 10, 10)


## Test 02  - small square in a small image

In [4]:
test02 = np.zeros((25,25),dtype = bool)
test02[7:17,7:17] = True

In [5]:
print(bbox_loop(test02))
print(my_bbox(test02))

(7, 7, 17, 17)
(0, 0, 25, 25)


## Test 03 - large square in a large image 

In [6]:
test03 = np.zeros((256,256),dtype = bool)
test03[64:192,64:192] = True

In [7]:
%timeit bbox_loop(test03)

72 ms ± 4.34 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
%timeit my_bbox(test03)

139 ns ± 4.68 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
